version: "3.9"
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app/api
    ports:
      - "8080:8080"